### ISSUE TITLE
bug: DTS breaking changes starting v2.4.x - errors on typescript 3.9

### ISSUE THREAD

**Issue by Hotell** [microsoft/keyborg#69]
Looks like after switch to [tsup](https://github.com/microsoft/keyborg/pull/58) leveraging their dts rolluping, the emit is transforming output in a way that breaks older TS versions that are supported in fluent.

```
export type {
  KeyborgFocusInEvent,
  KeyborgFocusInEventDetails,
} from "./FocusEvent";
export {
  getLastFocusedProgrammatically,
  nativeFocus,
  KEYBORG_FOCUSIN,
} from "./FocusEvent";
```

transforms to ⬇⬇⬇

```diff
export { 
KEYBORG_FOCUSIN, 
Keyborg, 
- type KeyborgCallback, 
- type KeyborgFocusInEvent, 
- type KeyborgFocusInEventDetails, 
createKeyborg, 
disposeKeyborg, 
getLastFocusedProgrammatically, 
nativeFocus, 
version 
};
```

This is currently breaking every pipeline in fluent monorepo, which will break any partner that is on TS lower than 4.5

https://uifabric.visualstudio.com/fabricpublic/_build/results?buildId=329898&view=logs&j=e51d397b-0a7b-5b89-4b48-0052e021371d&t=88c41216-94ff-5ca8-d686-48ce16c1eefc

_Fix:_

quickest fix ATM is to transform final dts output. either on your own by using TS AST or you can use https://github.com/sandersn/downlevel-dts

_Remarks:_

Going forward there is an initiative going on in fluent v-build to unify all repos around fluent to adhere to same tools, standards etc so things like this could never happen again. We should talk about this offline.

**Comment by Hotell** [comment]
folks not sure if this works as it fails our pipeline once the pinned version is removed https://github.com/microsoft/fluentui/pull/30279

**Comment by layershifter** [comment]
@Hotell 2.4.1 is on NPM 🚢
