### ISSUE TITLE
Keyborg instance is being disposed incorrectly. 

### ISSUE THREAD

**Issue by sujitykulkarni** [microsoft/keyborg#77]
I have **@fluentui/react-components v9.47.4** running, on top of 
 - React v18.2.0 
 - Typescript v5.4.4
 - vite v5.2.8. 
  
 While using FluentUI's Combobox, if I open the Listbox, but close it by clicking anywhere else in the page (making no changes in the option selection), I get following error in the console.

```
Keyborg instance k92 is being disposed incorrectly. 
Listbox<@http://localhost:3000/node_modules/.vite/deps/@fluentui_react-components.js?v=b3261b54:2087:36
span
Portal@http://localhost:3000/node_modules/.vite/deps/chunk-CYIF2TGV.js?v=c6d9a24b:241:35 [my-data:13441:25](http://localhost:3000/XXX)
    overrideMethod my-component:13441
    dispose Keyborg.ts:311
    dispose Keyborg.ts:271
    disposeKeyborg Keyborg.ts:361
    useKeyborg useKeyborg.js:14
   ...
```

This also has caused the Combobox lose its ability to show the border around the it's options if I navigate through those using ⬆️⬇️ arrows.

Above error **doesn't** surface if I change the Combobox selected options. 

_Not sure if this is FluentUI's issue, but being unable to reproduce this issue somewhere else, I prefer posting it here._

**Comment by mariefcornellier** [comment]
I am using Fluent v9 with React as well, the keyborg instance warning is spamming my console and it's getting worse and worse... I think it might have to do with the date picker

**Comment by miroslavstastny** [comment]
@mshoho could you please check this one asap?

**Comment by derekwsgray** [comment]
I'm getting this error as well when I close a Drawer with a Dropdown in it.
